kind: project
metadata:
  name: example-shapira
spec:
  functions:
  - url: train.py
    name: train
    kind: job
    image: mlrun/mlrun
    handler: train
  workflows: []
  artifacts:
  - kind: model
    metadata:
      key: model-test
      project: example-shapira
      iter: 0
      tree: b4106179cbdf45cb81c84b24dd218bbe
      hash: 937c31e31e08bb1197459fd9101ea57ee2d5489a
      tag: v1
    spec:
      target_path: v3io:///projects/example-shapira/artifacts/train-train/0/model/
      size: 3884
      db_key: model-test
      extra_data:
        model_spec.yaml: v3io:///projects/example-shapira/artifacts/train-train/0/model/model_spec.yaml
      model_file: model-test.pkl
      inputs:
      - name: '0'
        value_type: float
      - name: '1'
        value_type: float
      - name: '2'
        value_type: float
      - name: '3'
        value_type: float
      outputs:
      - name: y_0
        value_type: int
      framework: sklearn
      algorithm: SVC
      feature_stats:
        '0':
          count: 105.0
          mean: 5.8428571428571425
          std: 0.8333040287887755
          min: 4.3
          25%: 5.1
          50%: 5.8
          75%: 6.4
          max: 7.7
          hist:
          - - 3
            - 4
            - 2
            - 5
            - 16
            - 3
            - 3
            - 10
            - 10
            - 3
            - 8
            - 10
            - 7
            - 2
            - 5
            - 4
            - 1
            - 4
            - 1
            - 4
          - - 4.3
            - 4.47
            - 4.64
            - 4.81
            - 4.9799999999999995
            - 5.15
            - 5.32
            - 5.49
            - 5.66
            - 5.83
            - 6.0
            - 6.17
            - 6.34
            - 6.51
            - 6.68
            - 6.85
            - 7.02
            - 7.1899999999999995
            - 7.359999999999999
            - 7.53
            - 7.7
        '1':
          count: 105.0
          mean: 3.0095238095238095
          std: 0.41890971340534466
          min: 2.0
          25%: 2.8
          50%: 3.0
          75%: 3.3
          max: 4.2
          hist:
          - - 1
            - 2
            - 4
            - 3
            - 5
            - 4
            - 7
            - 9
            - 8
            - 21
            - 14
            - 5
            - 8
            - 4
            - 2
            - 2
            - 3
            - 1
            - 1
            - 1
          - - 2.0
            - 2.11
            - 2.22
            - 2.33
            - 2.44
            - 2.55
            - 2.66
            - 2.77
            - 2.88
            - 2.99
            - 3.1
            - 3.21
            - 3.3200000000000003
            - 3.43
            - 3.54
            - 3.6500000000000004
            - 3.7600000000000002
            - 3.87
            - 3.9800000000000004
            - 4.09
            - 4.2
        '2':
          count: 105.0
          mean: 3.8704761904761904
          std: 1.7213547778021447
          min: 1.1
          25%: 1.7
          50%: 4.3
          75%: 5.1
          max: 6.7
          hist:
          - - 7
            - 19
            - 5
            - 0
            - 0
            - 0
            - 1
            - 2
            - 2
            - 2
            - 9
            - 9
            - 8
            - 10
            - 6
            - 7
            - 8
            - 6
            - 1
            - 3
          - - 1.1
            - 1.3800000000000001
            - 1.6600000000000001
            - 1.94
            - 2.2199999999999998
            - 2.5
            - 2.78
            - 3.0599999999999996
            - 3.34
            - 3.6199999999999997
            - 3.9
            - 4.18
            - 4.459999999999999
            - 4.74
            - 5.02
            - 5.299999999999999
            - 5.58
            - 5.859999999999999
            - 6.139999999999999
            - 6.42
            - 6.7
        '3':
          count: 105.0
          mean: 1.239047619047619
          std: 0.7427204720712225
          min: 0.1
          25%: 0.4
          50%: 1.3
          75%: 1.8
          max: 2.5
          hist:
          - - 22
            - 4
            - 3
            - 1
            - 1
            - 0
            - 0
            - 7
            - 2
            - 3
            - 17
            - 8
            - 2
            - 2
            - 10
            - 7
            - 5
            - 1
            - 4
            - 6
          - - 0.1
            - 0.22
            - 0.33999999999999997
            - 0.45999999999999996
            - 0.58
            - 0.7
            - 0.82
            - 0.94
            - 1.06
            - 1.1800000000000002
            - 1.3
            - 1.42
            - 1.54
            - 1.6600000000000001
            - 1.78
            - 1.9
            - 2.02
            - 2.14
            - 2.2600000000000002
            - 2.38
            - 2.5
        y_0:
          count: 105.0
          mean: 1.0571428571428572
          std: 0.8065664576149014
          min: 0.0
          25%: 0.0
          50%: 1.0
          75%: 2.0
          max: 2.0
          hist:
          - - 31
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 37
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 37
          - - 0.0
            - 0.1
            - 0.2
            - 0.30000000000000004
            - 0.4
            - 0.5
            - 0.6000000000000001
            - 0.7000000000000001
            - 0.8
            - 0.9
            - 1.0
            - 1.1
            - 1.2000000000000002
            - 1.3
            - 1.4000000000000001
            - 1.5
            - 1.6
            - 1.7000000000000002
            - 1.8
            - 1.9000000000000001
            - 2.0
    status:
      state: created
  conda: ''
  source: git://github.com/GiladShapira94/test1.git#refs/heads/master
  origin_url: git://github.com/GiladShapira94/test1.git#refs/heads/master
  desired_state: online
